### ISSUE TITLE
Unable to load PPB_Label.pkl

### ISSUE THREAD

**Issue by Bibyutatsu** [ifyoungnet/ADMETlab#1]
Hi,
I am unable to load the pickle file named PPB_Label.pkl so please can you share the contents of the file. I just need the list of names of the descriptors used to predict the PPB value.

**Comment by ifyoungnet** [comment]
Hi,
try use sklearn to do this (under python2.7, sklearn 0.17.1).
from sklearn.externals import joblib
joblib.dump(clf,'xxx.pkl')
clf=joblib.load('xxx.pkl')

**Comment by ifyoungnet** [comment]
@Bibyutatsu 
Hi,
try use sklearn to do this (under python2.7, sklearn 0.17.1).
from sklearn.externals import joblib
joblib.dump(clf,'xxx.pkl')
clf=joblib.load('xxx.pkl')

**Comment by Bibyutatsu** [comment]
@ifyoungnet 
Hi,
Thank you very much for that help.
