### ISSUE TITLE
KeyError: 'max_depth' when use model

### ISSUE THREAD

**Issue by Lidweixiang** [ifyoungnet/ADMETlab#4]
Hi, A error occurred when I use the model downloaded from here. I test the example just like python run.py in python2 environment, and raise the KeyError: 'max_depth'! And I have no ideas about this. Thank you!

**Comment by ifyoungnet** [comment]
@Lidweixiang 
Please see the closed issues and find the specific version of each package in the py2 enviroment.

**Comment by Lidweixiang** [comment]
Thank you for your answer！
