### ISSUE TITLE
Known compounds on which this tool worked on

### ISSUE THREAD

**Issue by smruti241** [ifyoungnet/ADMETlab#5]
Hi,
Actually I want to understand how this ADMETSar works? I have gone through the papers but didnt understand properly. What are the known compounds or datasets you have worked? Can you give me some links or data regarding the inputs? How can we use those inputs for our research? Please let me know the whole scenario.
Thank you

**Comment by smruti241** [comment]
Hi,
Actually I want to understand how this ADMETLab works? I have gone through the papers but didnt understand properly. What are the known compounds or datasets you have worked? Can you give me some links or data regarding the inputs? How can we use those inputs for our research? Please let me know the whole scenario.
Thank you

**Comment by ifyoungnet** [comment]
@smruti241 
Dear sir,

Thank you for your feedback!

ADMETlab provides free service for prediction and evaluation. The corresponding models were also provided in GitHub for further use. example script and compound can be found in GitHub.

​A good news is that ADMETlab 2.0 is now online with more powerful functions like batch computation. 

http://admet.scbdd.com/​

https://admetmesh.scbdd.com/​
