### ISSUE TITLE
Question about the model.

### ISSUE THREAD

**Issue by ZeroDesigner** [ifyoungnet/ADMETlab#6]
Thanks for your good job.
I have run the example you offered and it works well.
And now, I noticed you offer 35 model files containing classfication and regression models.
I unzip several files and find they are same, no matter in the classfication or  regression models.
So, could you tell whether it's right I use random one model  in these files to predict admet.
Or I need to run all the files to do predictions and summary the results ?

<img width="709" alt="Screen Shot 2021-03-03 at 11 55 45 AM" src="https://user-images.githubusercontent.com/32703906/109750610-b7857180-7c17-11eb-9816-455a3da99a33.png">
<img width="751" alt="Screen Shot 2021-03-03 at 11 55 34 AM" src="https://user-images.githubusercontent.com/32703906/109750614-b94f3500-7c17-11eb-838a-44ceb8dbbefa.png">
<img width="642" alt="Screen Shot 2021-03-03 at 11 54 33 AM" src="https://user-images.githubusercontent.com/32703906/109750620-bce2bc00-7c17-11eb-9735-eccad7d39b0f.png">
<img width="749" alt="Screen Shot 2021-03-03 at 11 54 16 AM" src="https://user-images.githubusercontent.com/32703906/109750623-be13e900-7c17-11eb-8b08-2e76aadf6c6b.png">

**Comment by ifyoungnet** [comment]
@luskyqi1995 sorry, at present, we have not encountered this problem. Theoretically, there is only one model after unzip.
